### ISSUE TITLE
Make Linux condalock file

### ISSUE THREAD

**Issue by FrickTobias** [FrickTobias/nd2tools#4]
# Problem

Currently there is a conda problem giving an error when running condalock. When it is resolved the `environment.linux.lock.yml` file should be remade using `bash misc/condalock.sh linux`

`bash misc/condalock.sh osx` works as normal.

The current place holder linux file is just a copy of `environment.yml`

# Error

```
Verifying transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/tobiasfrick/miniconda/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/tobiasfrick/miniconda/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/tobiasfrick/miniconda/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 118, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/Users/tobiasfrick/miniconda/lib/python3.8/site-packages/conda_env/installers/conda.py", line 40, in install
        unlink_link_transaction.execute()
      File "/Users/tobiasfrick/miniconda/lib/python3.8/site-packages/conda/core/link.py", line 244, in execute
        self.verify()
      File "/Users/tobiasfrick/miniconda/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/Users/tobiasfrick/miniconda/lib/python3.8/site-packages/conda/core/link.py", line 231, in verify
        exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)
      File "/Users/tobiasfrick/miniconda/lib/python3.8/site-packages/conda/core/link.py", line 590, in _verify
        for exc in self.verify_executor.map(UnlinkLinkTransaction._verify_individual_level,
      File "/Users/tobiasfrick/miniconda/lib/python3.8/site-packages/conda/common/io.py", line 525, in map
        yield func(thing)
      File "/Users/tobiasfrick/miniconda/lib/python3.8/site-packages/conda/core/link.py", line 411, in _verify_individual_level
        error_result = axn.verify()
      File "/Users/tobiasfrick/miniconda/lib/python3.8/site-packages/conda/core/path_actions.py", line 323, in verify
        source_size_in_bytes = getsize(self.source_full_path)
      File "/Users/tobiasfrick/miniconda/lib/python3.8/genericpath.py", line 50, in getsize
        return os.stat(filename).st_size
    OSError: [Errno 62] Too many levels of symbolic links: '/Users/tobiasfrick/miniconda/pkgs/ncurses-6.2-h58526e2_4/share/terminfo/N/NCR260VT300WPP'

`$ /Users/tobiasfrick/miniconda/bin/conda-env create -n blrtmp-7778-linux -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=nd2tools
                CONDA_EXE=/Users/tobiasfrick/miniconda/bin/conda
             CONDA_PREFIX=/Users/tobiasfrick/miniconda/envs/nd2tools
    CONDA_PROMPT_MODIFIER=(nd2tools)
         CONDA_PYTHON_EXE=/Users/tobiasfrick/miniconda/bin/python
               CONDA_ROOT=/Users/tobiasfrick/miniconda
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/tobiasfrick/miniconda/envs/nd2tools/bin:/usr/local/git/bin:/sw/
                          bin:/usr/local/bin:/usr/local:/usr/local/sbin:/usr/local/mysql/bin:/Us
                          ers/tobiasfrick/Library/Python/3.9/bin:/Users/tobiasfrick/external/cel
                          lranger-5.0.1:/Users/tobiasfrick/miniconda/condabin:/usr/local/bin:/us
                          r/bin:/bin:/usr/sbin:/sbin:/Users/tobiasfrick/external/sratoolkit.2.10
                          .9-mac64/bin:/usr/local/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : nd2tools
    active env location : /Users/tobiasfrick/miniconda/envs/nd2tools
            shell level : 1
       user config file : /Users/tobiasfrick/.condarc
 populated config files : /Users/tobiasfrick/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/tobiasfrick/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/tobiasfrick/miniconda/pkgs
                          /Users/tobiasfrick/.conda/pkgs
       envs directories : /Users/tobiasfrick/miniconda/envs
                          /Users/tobiasfrick/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Darwin/20.3.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.

```

**Comment by FrickTobias** [comment]
Moved to conda-lock
